version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '3001:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: postgres:13.3
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
volumes:
  postgres:
